name: Deploy production

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build-api-and-release-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16.18.1"

      - name: Checkout production
        run: |
          git config user.email "igortrindademe@gmail.com"
          git config user.name "Igor Trindade"
          git checkout production
          git pull
          git merge main

      - name: Install dependencies and build frontend
        run: |
          npm ci
          npm run generate

      - name: Push changes and tags to production branch
        run: |
          git push --follow-tags origin production
